### ISSUE TITLE
Contexts cannot be parsed anymore

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#1]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

since the new refactoring

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/1

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
