### ISSUE TITLE
Fix proof obligations generator for event splitting

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#13]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

The right safety properties are not generated when splitting events. See notes

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/13

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
