### ISSUE TITLE
Testing server

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#17]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

Setup a server to run quickCheck periodically

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/17

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
