### ISSUE TITLE
Benchmark the Haskell z3 bindings

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#18]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

... to avoid serializing proof obligations

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/18

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
