### ISSUE TITLE
Investigate alternate testing frameworks

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#19]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

Candidates:
- doctest
- HUnit
- HSpec
- test-framework
- tasty

Important: 
- Test must be runnable in parallel
- The infrastructure for testing proof obligations must be portable to the new testing framework
- Should have good support for QuickCheck properties (including when collected by forAllProperties)

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/19

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
