### ISSUE TITLE
Type-based arity invariant in Expr

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#2]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

The thing is to use type checking to increase the safety of expression syntax trees. 

If I remove the type parameters and simplify, function application is declared as:

| FunApp Fun [Expr] -- Line 66 in Logic.Expr.Expr

where Fun contains [Type] as one of its components. One invariant that I need to rely on is that the list of expressions and the list of types have the same length. We can use existential types to enforce that invariant. All we need to do is give Fun a type parameter that stands for its arity and use a different data structure than list - let's call them vectors - which has a type parameter that stands for its length. Function application becomes:

| forall arity. FunApp (Fun arity) (Vector arity Expr)

Now the parser is responsible of checking the arity of functions applied to arguments and the rest of the code can safely assume that it is consistent (the type checker won't let it be inconsistent).

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/2

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
