### ISSUE TITLE
Consider using GHC-shake as the build system

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#20]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

https://github.com/ezyang/ghc-shake

Should replace Build.hs, cabal or stack

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/20

**Comment by aminb** [comment]
*Original comment by* **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**:

----------------------------------------

We will need GHC 8.0 for that

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
