### ISSUE TITLE
Find and remove dead code

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#21]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

... use GHC code coverage features

Also find untested code and add test cases for it

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/21

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
