### ISSUE TITLE
command line options to only run QuickCheck properties

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#22]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

... In suite/Test.hs

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/22

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
