### ISSUE TITLE
Continuous Integration Server

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#23]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

Needs:
- build every branch when pushed
- run test suite
- push build status on bit bucket
- email everyone when build fails

Candidates:
- Jenkins
- Circle CI

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/23

**Comment by aminb** [comment]
*Original comment by* **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**:

----------------------------------------

[GitLab CI](https://about.gitlab.com/gitlab-ci/) is another potential candidate.

Also, this reddit thread looks quite useful to see what others use:
https://www.reddit.com/r/haskell/comments/34m4bq/people_using_haskell_in_production_what_is_your/

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
