### ISSUE TITLE
Add QuickCheck properties for expression parser and scanner

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#26]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

And split Document.MachineSpec

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/26

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
