### ISSUE TITLE
Add the latex files to the test suite

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#27]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

When we run the test suite we should get an error if any latex file from the test cases is not valid latex

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/27

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
