### ISSUE TITLE
Retirement of Latex.Scanner

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#3]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

I would like to retire the model Latex.Scanner on which Logic.Expr.Parser relies (I think Latex.Parser no longer does) because parsec is a better way of writing that code. After you've separated expression parsing from type checking, when you're ready, rewriting the expression parser using parsec would be very useful.

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/3

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
