### ISSUE TITLE
Rename variables that use built-in z3 keyword

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#30]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

```
(declare-const rem Int)
```

produces

```
(error "line 36 column 31: invalid declaration, builtin symbol rem")
```

we should use

```
(declare-const b$rem Int)
```

instead

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/30

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
