### ISSUE TITLE
Use de Bruijn encoding for the AST

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#31]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

redesign
- Expr
- Types
- Sequent
- ProofTree
- Machine
- Theory
- LivenessProof
- Property and PropertySet
- Event

to get their types to reflect scope

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/31

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
