### ISSUE TITLE
Move projects in separate repositories

### ISSUE THREAD

**Issue by bandali** [unitb/literate-unitb#32]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---
- [x] Web prover: [literate-unitb/unitb-web](/literate-unitb/unitb-web)
- [x] existential: [literate-unitb/existential](/literate-unitb/existential)
- [x] tex2png-hs: [literate-unitb/tex2png-hs](/literate-unitb/tex2png-hs)
- [x] printf-th: [literate-unitb/printf-th](/literate-unitb/printf-th)
- [x] invariants: [literate-unitb/invariants](/literate-unitb/invariants)
- [x] axiomatic-classes: [literate-unitb/axiomatic-classes](/literate-unitb/axiomatic-classes)

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/32

**Comment by aminb** [comment]
Done.

Next step: sort out the build issues and then remove the libraries from the main (this) repo.

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
