### ISSUE TITLE
Port interactive interface to Reactive.Banana

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#7]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/7

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
