### ISSUE TITLE
Delay redundant proofs

### ISSUE THREAD

**Issue by aminb** [unitb/literate-unitb#8]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

---

When re-parsing a model some proof obligations remain the same and they do not have to be proved again. Other proof obligations remain mostly the same with the exception of added assumptions. If they were proved successfully already, the _truth_ of the new proof obligation follows. However, more assumptions make the task of the theorem prover harder and retrying the proof obligation might result in a failure. Most of the time, it shouldn't but we want only want to call "proved" the proof obligations on which the theorem prover succeeded.

On the other hand, every time an invariant is added to a model, most of its proof obligations get a new assumption and retrying all of them for every new invariant becomes expensive and delays the proof of more important, newer proof obligations. 

The idea is to delay (maybe by 1 minute, maybe by 5) the starting of provers on augmented proof obligations (the ones that were proved and for which the only change is adding assumptions) and only starting them when no others need to be proved.

---
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/8

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
